name: Hello World

on: push # Triggers the workflow when you push the changes

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello, World! ðŸš€"

  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: test hello-world
        run: echo "Running tests âœ…"

